name: Python Code Style Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Ensure the latest version is used

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      - name: Run Checkstyle (flake8) and Save Report
        run: |
          flake8 . --exit-zero --output-file=flake8_report.txt
        continue-on-error: true  # Ensures workflow doesn't fail on errors

      - name: Print Flake8 Warnings
        run: |
          cat flake8_report.txt || echo "No warnings found."

      - name: Upload Checkstyle Report as Artifact
        uses: actions/upload-artifact@v4  # Use the latest version
        with:
          name: flake8-report
          path: flake8_report.txt
