name: Run Unit Tests for Task Sorter

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Use the latest version of checkout

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest unittest mock  # Ensure testing tools are available

      - name: Run Unit Tests
        run: |
          pytest tests/ --disable-warnings --maxfail=3
        continue-on-error: false  # Fail the CI if tests fail

      - name: Upload Test Report (if exists)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report
          path: tests/test-results.log
